In [10]:
import pandas as pd
data = pd.read_csv("dataset/stud_testing_final_updated.csv")
data
df = data.copy()
df[:8]

Drawing  Dancing  Singing  Sports  VideoGame  Acting  Travelling  \
0        0        0        0       0          0       0           0   
1        0        1        1       0          0       0           0   
2        0        0        0       0          0       0           0   
3        0        0        0       0          0       0           1   
4        0        0        0       0          0       0           0   
5        0        0        0       0          0       0           0   
6        0        0        0       0          0       0           1   
7        1        0        0       0          1       0           0   

   Gardening  Animals  Photography  ...  Engeeniering  Doctor  Pharmisist  \
0          0        0            0  ...             0       0           0   
1          0        0            0  ...             0       0           0   
2          0        0            0  ...             0       0           0   
3          0        0            0  ...             0       0           0   
4          0        0            0  ...             0       0           0   
5          0        0            0  ...             0       0           0   
6          0        0            1  ...             0       0           0   
7          0        0            0  ...             0       0           0   

   Cycling  Knitting  Director  Journalism  Bussiness  ListeningMusic  \
0        0         0         1           0          1               0   
1        0         0         1           0          0               0   
2        0         0         0           0          0               0   
3        0         0         0           1          0               0   
4        0         1         0           0          0               0   
5        0         0         0           0          1               0   
6        0         0         0           0          0               1   
7        0         0         0           0          0               0   

    Courses  
0  commerce  
1      arts  
2       law  
3      arts  
4      arts  
5  business  
6  business  
7      arts  

[8 rows x 60 columns]

In [11]:
df.columns

Index(['Drawing', 'Dancing', 'Singing', 'Sports', 'VideoGame', 'Acting',
       'Travelling', 'Gardening', 'Animals', 'Photography', 'Teaching',
       'Exercise', 'Coding', 'ElectricityComponents', 'MechanicParts',
       'ComputerParts', 'Researching', 'Architecture', 'HistoricCollection',
       'Botany', 'Zoology', 'Physics', 'Accounting', 'Economics', 'Sociology',
       'Geography', 'Psycology', 'History', 'Science', 'BussinessEducation',
       'Chemistry', 'Mathematics', 'Biology', 'Makeup', 'Designing',
       'ContentWriting', 'Crafting', 'Literature', 'Reading', 'Cartooning',
       'Debating', 'Asrtology', 'Hindi', 'French', 'English', 'Urdu',
       'OtherLanguage', 'SolvingPuzzles', 'Gymnastics', 'Yoga', 'Engeeniering',
       'Doctor', 'Pharmisist', 'Cycling', 'Knitting', 'Director', 'Journalism',
       'Bussiness', 'ListeningMusic', 'Courses'],
      dtype='object')

In [12]:
df['Courses'].unique()

array(['commerce', 'arts', 'law', 'business', 'architecture',
       'engineering', 'medicine', 'science'], dtype=object)

In [13]:
# df['Courses'].value_counts()

In [14]:
df.shape

(517, 60)

In [15]:
course_serials = {
    'commerce':0, 
    'arts':1, 
    'law':2, 
    'business':3, 
    'architecture':4,
    'engineering':5, 
    'medicine':6, 
    'science':7
}

df['Courses'] = df['Courses'].map(course_serials)

In [16]:
# course_serials = {
#     'BBA- Bachelor of Business Administration': 0,
#     'BEM- Bachelor of Event Management': 1,
#     'Integrated Law Course- BA + LL.B': 2,
#     'BJMC- Bachelor of Journalism and Mass Communication': 3,
#     'BFD- Bachelor of Fashion Designing': 4,
#     'BBS- Bachelor of Business Studies': 5,
#     'BTTM- Bachelor of Travel and Tourism Management': 6,
#     'BVA- Bachelor of Visual Arts': 7,
#     'BA in History': 8,
#     'B.Arch- Bachelor of Architecture': 9,
#     'BCA- Bachelor of Computer Applications': 10,
#     'B.Sc.- Information Technology': 11,
#     'B.Sc- Nursing': 12,
#     'BPharma- Bachelor of Pharmacy': 13,
#     'BDS- Bachelor of Dental Surgery': 14,
#     'Animation, Graphics and Multimedia': 15,
#     'B.Sc- Applied Geology': 16,
#     'B.Sc.- Physics': 17,
#     'B.Sc. Chemistry': 18,
#     'B.Sc. Mathematics': 19,
#     'B.Tech.-Civil Engineering': 20,
#     'B.Tech.-Computer Science and Engineering': 21,
#     'B.Tech.-Electronics and Communication Engineering': 22,
#     'B.Tech.-Electrical and Electronics Engineering': 23,
#     'B.Tech.-Mechanical Engineering': 24,
#     'B.Com- Bachelor of Commerce': 25,
#     'BA in Economics': 26,
#     'CA- Chartered Accountancy': 27,
#     'CS- Company Secretary': 28,
#     'Diploma in Dramatic Arts': 29,
#     'MBBS': 30,
#     'Civil Services': 31,
#     'BA in English': 32,
#     'BA in Hindi': 33,
#     'B.Ed.': 34
# }


# df['Courses'] = df['Courses'].map(course_serials)

In [17]:
df.head()

Drawing  Dancing  Singing  Sports  VideoGame  Acting  Travelling  \
0        0        0        0       0          0       0           0   
1        0        1        1       0          0       0           0   
2        0        0        0       0          0       0           0   
3        0        0        0       0          0       0           1   
4        0        0        0       0          0       0           0   

   Gardening  Animals  Photography  ...  Engeeniering  Doctor  Pharmisist  \
0          0        0            0  ...             0       0           0   
1          0        0            0  ...             0       0           0   
2          0        0            0  ...             0       0           0   
3          0        0            0  ...             0       0           0   
4          0        0            0  ...             0       0           0   

   Cycling  Knitting  Director  Journalism  Bussiness  ListeningMusic  Courses  
0        0         0         1           0          1               0        0  
1        0         0         1           0          0               0        1  
2        0         0         0           0          0               0        2  
3        0         0         0           1          0               0        1  
4        0         1         0           0          0               0        1  

[5 rows x 60 columns]

In [18]:
from imblearn.over_sampling import SMOTE

In [19]:
df['Courses'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
df.tail()

Drawing  Dancing  Singing  Sports  VideoGame  Acting  Travelling  \
512        1        0        1       1          1       1           1   
513        1        1        0       1          0       0           0   
514        1        0        1       0          1       0           1   
515        1        0        1       0          1       0           1   
516        1        0        1       0          1       0           1   

     Gardening  Animals  Photography  ...  Engeeniering  Doctor  Pharmisist  \
512          0        1            0  ...             1       1           1   
513          0        1            1  ...             0       0           1   
514          0        1            0  ...             1       0           0   
515          0        1            0  ...             1       0           0   
516          0        1            0  ...             1       0           0   

     Cycling  Knitting  Director  Journalism  Bussiness  ListeningMusic  \
512        0         1         0           0          1               1   
513        0         1         0           1          0               0   
514        1         0         0           1          1               1   
515        1         0         0           1          1               1   
516        1         0         0           1          1               1   

     Courses  
512        1  
513        5  
514        1  
515        1  
516        1  

[5 rows x 60 columns]

In [21]:
smote = SMOTE(random_state = 42)

X = df.drop('Courses', axis=1)
y = df['Courses']

X_resampled, y_resampled = smote.fit_resample(X,y)

In [22]:
# df['Courses'].unique()

In [23]:
X_resampled

Drawing  Dancing  Singing  Sports  VideoGame  Acting  Travelling  \
0           0        0        0       0          0       0           0   
1           0        1        1       0          0       0           0   
2           0        0        0       0          0       0           0   
3           0        0        0       0          0       0           1   
4           0        0        0       0          0       0           0   
...       ...      ...      ...     ...        ...     ...         ...   
1467        0        0        0       0          0       1           0   
1468        0        0        0       0          0       1           0   
1469        0        0        1       1          0       1           1   
1470        0        1        0       1          0       0           1   
1471        1        0        1       1          0       0           0   

      Gardening  Animals  Photography  ...  Yoga  Engeeniering  Doctor  \
0             0        0            0  ...     0             0       0   
1             0        0            0  ...     0             0       0   
2             0        0            0  ...     0             0       0   
3             0        0            0  ...     0             0       0   
4             0        0            0  ...     0             0       0   
...         ...      ...          ...  ...   ...           ...     ...   
1467          0        0            0  ...     0             0       0   
1468          0        0            1  ...     0             0       1   
1469          0        0            1  ...     1             0       0   
1470          1        0            0  ...     0             0       0   
1471          0        0            0  ...     0             0       1   

      Pharmisist  Cycling  Knitting  Director  Journalism  Bussiness  \
0              0        0         0         1           0          1   
1              0        0         0         1           0          0   
2              0        0         0         0           0          0   
3              0        0         0         0           1          0   
4              0        0         1         0           0          0   
...          ...      ...       ...       ...         ...        ...   
1467           1        0         0         0           1          0   
1468           1        0         0         0           1          0   
1469           0        1         0         0           0          1   
1470           0        1         0         1           0          0   
1471           0        1         0         0           1          1   

      ListeningMusic  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
1467               0  
1468               0  
1469               0  
1470               0  
1471               0  

[1472 rows x 59 columns]

In [24]:
y_resampled

0       0
1       1
2       2
3       1
4       1
       ..
1467    7
1468    7
1469    7
1470    7
1471    7
Name: Courses, Length: 1472, dtype: int64

In [25]:
y_resampled.value_counts()

Courses
0    184
1    184
2    184
3    184
4    184
5    184
6    184
7    184
Name: count, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state = 42)

In [27]:
from sklearn.preprocessing import StandardScaler
scaler  =StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings("ignore")

In [29]:
models = {
    "Logistic Regression": LogisticRegression(),
    "Support Vector Classifier" : SVC(),
    "Random Forest Classifier": RandomForestClassifier(),
    "K Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Gaussian Naive Bayes" : GaussianNB(),
    "AdaBoost Classifier" : AdaBoostClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    "XGBoost Classifier": XGBClassifier(use_label_encoder=False, eval_metric='mlogloss') 
}

In [30]:
for name, model in models.items():
    print("="*50)
    print("\n\nModel = ", name) 

    model.fit(X_train_scaled, y_train)

    y_pred = model.predict(X_test_scaled)

    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)

    conf_matrix = confusion_matrix(y_test, y_pred)

    print("Accuracy = ", accuracy)
    print("\nClassification Report :\n", classification_rep)
    print("\nConfusion matrix: \n", conf_matrix)



Model =  Logistic Regression
Accuracy =  0.5627118644067797

Classification Report :
               precision    recall  f1-score   support

           0       0.42      0.31      0.36        42
           1       0.33      0.26      0.29        39
           2       0.91      0.91      0.91        32
           3       0.77      0.85      0.81        40
           4       0.72      0.97      0.82        34
           5       0.37      0.30      0.33        43
           6       0.35      0.51      0.42        35
           7       0.62      0.53      0.57        30

    accuracy                           0.56       295
   macro avg       0.56      0.58      0.56       295
weighted avg       0.55      0.56      0.55       295


Confusion matrix: 
 [[13  4  1  4  3  6  8  3]
 [ 4 10  1  4  3 10  7  0]
 [ 0  2 29  0  0  0  1  0]
 [ 0  1  0 34  0  2  3  0]
 [ 0  0  0  0 33  0  1  0]
 [ 7  4  1  1  5 13  9  3]
 [ 1  6  0  0  2  4 18  4]
 [ 6  3  0  1  0  0  4 16]]


Model =  Support Vect

In [31]:
model = RandomForestClassifier()

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print("Accuracy score: ", accuracy_score(y_test, y_pred))
print("Report: ", classification_report(y_test, y_pred))
print("Confusion Matrix: ", confusion_matrix(y_test, y_pred))

Accuracy score:  0.8711864406779661
Report:                precision    recall  f1-score   support

           0       0.81      0.93      0.87        42
           1       0.72      0.59      0.65        39
           2       1.00      1.00      1.00        32
           3       0.95      1.00      0.98        40
           4       1.00      1.00      1.00        34
           5       0.82      0.74      0.78        43
           6       0.86      0.86      0.86        35
           7       0.82      0.90      0.86        30

    accuracy                           0.87       295
   macro avg       0.87      0.88      0.87       295
weighted avg       0.87      0.87      0.87       295

Confusion Matrix:  [[39  3  0  0  0  0  0  0]
 [ 5 23  0  1  0  5  2  3]
 [ 0  0 32  0  0  0  0  0]
 [ 0  0  0 40  0  0  0  0]
 [ 0  0  0  0 34  0  0  0]
 [ 2  3  0  0  0 32  3  3]
 [ 0  3  0  0  0  2 30  0]
 [ 2  0  0  1  0  0  0 27]]


In [32]:
print("Predicted Labels: ", model.predict(X_test_scaled[10].reshape(1, -1))[0])
print("Actual predictions", y_test.iloc[10])

Predicted Labels:  2
Actual predictions 2


In [33]:
print("Predicted Labels: ", model.predict(X_test_scaled[100].reshape(1, -1))[0])
print("Actual predictions", y_test.iloc[100])

Predicted Labels:  6
Actual predictions 5


In [34]:
print("Predicted Labels: ", model.predict(X_test_scaled[120].reshape(1, -1))[0])
print("Actual predictions", y_test.iloc[120])

Predicted Labels:  4
Actual predictions 4


In [35]:
print("Predicted Labels: ", model.predict(X_test_scaled[30].reshape(1, -1))[0])
print("Actual predictions", y_test.iloc[30])

Predicted Labels:  6
Actual predictions 6


In [36]:
import pickle

#writing to the file
pickle.dump(scaler, open("Models/scaler2.pkl", "wb"))
pickle.dump(model, open("Models/model2.pkl", "wb"))

In [37]:
# reading the file
scaler = pickle.load(open("Models/scaler2.pkl", "rb"))
model = pickle.load(open("Models/model2.pkl", "rb"))

In [39]:
import numpy as np

# class_names = ['BBA- Bachelor of Business Administration',
#     'BEM- Bachelor of Event Management',
#     'Integrated Law Course- BA + LL.B',
#     'BJMC- Bachelor of Journalism and Mass Communication',
#     'BFD- Bachelor of Fashion Designing',
#     'BBS- Bachelor of Business Studies',
#     'BTTM- Bachelor of Travel and Tourism Management',
#     'BVA- Bachelor of Visual Arts', 
#     'BA in History',
#     'B.Arch- Bachelor of Architecture',
#     'BCA- Bachelor of Computer Applications',
#     'B.Sc.- Information Technology', 
#     'B.Sc- Nursing',
#     'BPharma- Bachelor of Pharmacy', 
#     'BDS- Bachelor of Dental Surgery',
#     'Animation, Graphics and Multimedia', 
#     'B.Sc- Applied Geology',
#     'B.Sc.- Physics', 
#     'B.Sc. Chemistry',
#     'B.Sc. Mathematics',
#     'B.Tech.-Civil Engineering',
#     'B.Tech.-Computer Science and Engineering',
#     'B.Tech.-Electronics and Communication Engineering',
#     'B.Tech.-Electrical and Electronics Engineering',
#     'B.Tech.-Mechanical Engineering', 
#     'B.Com- Bachelor of Commerce',
#     'BA in Economics', 
#     'CA- Chartered Accountancy',
#     'CS- Company Secretary', 
#     'Diploma in Dramatic Arts', 
#     'MBBS',
#     'Civil Services', 
#     'BA in English', 
#     'BA in Hindi', 
#     'B.Ed.']

class_names = [
    'commerce', 'arts', 'law', 'business', 'architecture', 'engineering', 'medicine', 'science']


def Recommendations(Drawing, Dancing, Singing, Sports, VideoGame, Acting, Travelling, Gardening, Animals, 
                    Photography, Teaching, Exercise, Coding, ElectricityComponents, MechanicParts, 
                    ComputerParts, Researching, Architecture, HistoricCollection, Botany, Zoology, Physics, Accounting, 
                    Economics, Sociology, Geography, Psycology, History, Science, BussinessEducation, Chemistry, Mathematics, 
                    Biology, Makeup, Designing, ContentWriting, Crafting, Literature, Reading, Cartooning, Debating, Asrtology, 
                    Hindi, French, English, Urdu, OtherLanguage, SolvingPuzzles, Gymnastics, Yoga, Engeeniering, Doctor, 
                    Pharmisist, Cycling, Knitting, Director, Journalism, Bussiness, ListeningMusic):

    # Create feature array
    feature_array = np.array([[Drawing, Dancing, Singing, Sports, VideoGame, Acting, Travelling, Gardening, Animals, 
                               Photography, Teaching, Exercise, Coding, ElectricityComponents, MechanicParts, 
                               ComputerParts, Researching, Architecture, HistoricCollection, Botany, Zoology, 
                               Physics, Accounting, Economics, Sociology, Geography, Psycology, History, Science, 
                               BussinessEducation, Chemistry, Mathematics, Biology, Makeup, Designing, ContentWriting, 
                               Crafting, Literature, Reading, Cartooning, Debating, Asrtology, Hindi, French, English, 
                               Urdu, OtherLanguage, SolvingPuzzles, Gymnastics, Yoga, Engeeniering, Doctor, Pharmisist, 
                               Cycling, Knitting, Director, Journalism, Bussiness, ListeningMusic]])

    # Scale features
    scaled_features = scaler.transform(feature_array)

    # Predict using the model
    probabilities = model.predict_proba(scaled_features)

    # Get top five predicted classes along with their probabilities 
    top_classes_idx = np.argsort(-probabilities[0])[:5]   

    top_classes_name_probs = [(class_names[idx], probabilities[0][idx]) for idx in top_classes_idx]

    return top_classes_name_probs


In [40]:
final_recommendations = Recommendations(
    Drawing=1,
    Dancing=0,
    Singing=1,
    Sports=0,
    VideoGame=1,
    Acting=0,
    Travelling=1,
    Gardening=0,
    Animals=1,
    Photography=0,
    Teaching=1,
    Exercise=0,
    Coding=1,
    ElectricityComponents=0,
    MechanicParts=0,
    ComputerParts=1,
    Researching=1,
    Architecture=0,
    HistoricCollection=0,
    Botany=0,
    Zoology=0,
    Physics=1,
    Accounting=0,
    Economics=1,
    Sociology=0,
    Geography=0,
    Psycology=1,
    History=0,
    Science=1,
    BussinessEducation=0,
    Chemistry=1,
    Mathematics=1,
    Biology=0,
    Makeup=0,
    Designing=1,
    ContentWriting=0,
    Crafting=0,
    Literature=1,
    Reading=1,
    Cartooning=0,
    Debating=1,
    Asrtology=0,
    Hindi=0,
    French=0,
    English=1,
    Urdu=0,
    OtherLanguage=0,
    SolvingPuzzles=1,
    Gymnastics=0,
    Yoga=1,
    Engeeniering=1,
    Doctor=0,
    Pharmisist=0,
    Cycling=1,
    Knitting=0,
    Director=0,
    Journalism=1,
    Bussiness=1,
    ListeningMusic=1
)

print("Top recommended studies with probabilities : ")
print("=="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")

Top recommended studies with probabilities : 
arts with probability 0.96
engineering with probability 0.03
medicine with probability 0.01
commerce with probability 0.0
business with probability 0.0


In [43]:
input_data = {
    'Drawing': 1,
    'Dancing': 0,
    'Singing': 1,
    'Sports': 0,
    'VideoGame': 1,
    'Acting': 0,
    'Travelling': 1,
    'Gardening': 0,
    'Animals': 1,
    'Photography': 0,
    'Teaching': 1,
    'Exercise': 0,
    'Coding': 1,
    'ElectricityComponents': 0,
    'MechanicParts': 0,
    'ComputerParts': 1,
    'Researching': 1,
    'Architecture': 0,
    'HistoricCollection': 0,
    'Botany': 0,
    'Zoology': 0,
    'Physics': 1,
    'Accounting': 0,
    'Economics': 1,
    'Sociology': 0,
    'Geography': 0,
    'Psycology': 1,
    'History': 0,
    'Science': 1,
    'BussinessEducation': 0,
    'Chemistry': 1,
    'Mathematics': 1,
    'Biology': 0,
    'Makeup': 0,
    'Designing': 1,
    'ContentWriting': 0,
    'Crafting': 0,
    'Literature': 1,
    'Reading': 1,
    'Cartooning': 0,
    'Debating': 1,
    'Asrtology': 0,
    'Hindi': 0,
    'French': 0,
    'English': 1,
    'Urdu': 0,
    'OtherLanguage': 0,
    'SolvingPuzzles': 1,
    'Gymnastics': 0,
    'Yoga': 1,
    'Engeeniering': 1,
    'Doctor': 0,
    'Pharmisist': 0,
    'Cycling': 1,
    'Knitting': 0,
    'Director': 0,
    'Journalism': 1,
    'Bussiness': 1,
    'ListeningMusic': 1
}

# Get recommendation from your model
final_recommendations = Recommendations(**input_data)


top_course = final_recommendations[0][0]  # course name
input_data['Courses'] = top_course


# Convert to a DataFrame
df = pd.DataFrame([input_data])

# Save to CSV (append if exists, or create new)
csv_path = 'dataset/stud_testing_final_updated.csv'
try:
    existing_df = pd.read_csv(csv_path)
    updated_df = pd.concat([existing_df, df], ignore_index=True)
except FileNotFoundError:
    print("File not found, creating new")
    updated_df = df

# Save back to CSV
updated_df.to_csv(csv_path, index=False)

print("Prediction saved successfully!")

Prediction saved successfully!
